#define SIMPLE_HTTP_RTOS_MODE 1
//enable support for RTSP methods (DESCRIBE,SETUP,PLAY,PAUSE,TEARDOWN)
#define SIMPLE_HTTP_RTSP_SUPPORT 0
//enables use of ESP_LOG_LEVEL_LOCAL
#define SIMPLE_HTTP_ESP_LOG_SUPPORT 1